server:
  port: 9090
spring:
  application:
    name: 02-UserMana-Project
    
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/02_Projectdb
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  